---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system

spec:
  selector:
    matchLabels:
      app: helm
      name: tiller
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      tolerations:
      - key: "AcceptType"
        operator: Equal
        value: "SysTool"
        effect: NoSchedule
      # nodeSelector: 
        # kubernetes.io/hostname: 10.0.0.252
      
      automountServiceAccountToken: true
      containers:
      - env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "5"
        - name: TILLER_TLS_VERIFY
          value: "1"
        - name: TILLER_TLS_ENABLE
          value: "1"
        - name: TILLER_TLS_CERTS
          value: /etc/certs
        image: easzlab/tiller:v2.14.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports:
        - containerPort: 44134
          name: tiller
        - containerPort: 44135
          name: http
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
        volumeMounts:
        - mountPath: /etc/certs
          name: tiller-certs
          readOnly: true
      serviceAccountName: tiller
      volumes:
      - name: tiller-certs
        secret:
          secretName: tiller-secret
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  ports:
  - name: tiller
    port: 44134
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1RENDQXFDZ0F3SUJBZ0lVVk5uTDdqNkt3TTNhSlR4bHd1eDhnRHcvOUtzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lURUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0VoaGJtZGFhRzkxTVFzd0NRWURWUVFIRXdKWQpVekVNTUFvR0ExVUVDaE1EYXpoek1ROHdEUVlEVlFRTEV3WlRlWE4wWlcweEV6QVJCZ05WQkFNVENtdDFZbVZ5CmJtVjBaWE13SUJjTk1qQXdOREEzTURrMU1UQXdXaGdQTWpFeU1EQXpNVFF3T1RVeE1EQmFNR0V4Q3pBSkJnTlYKQkFZVEFrTk9NUkV3RHdZRFZRUUlFd2hJWVc1bldtaHZkVEVMTUFrR0ExVUVCeE1DV0ZNeEREQUtCZ05WQkFvVApBMnM0Y3pFUE1BMEdBMVVFQ3hNR1UzbHpkR1Z0TVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXJha3lUa2FrMHIvMDVyYWNid2cxeGJxYkExajUKSE5nTWxqMUUvcjVjVDA1NjJ1R2hpMU9jZVRmMlZkUU9FVm9lcm04ZVFSVjdTMnF4aTNWOUJPK0crdWlTZjJXQgpnSnh2RmRmMVF4WjVGNEk3NDFJRjFFZWhXZEh5dFBQZ2V1ZU9WdE9pei82a3VQMzYwZ2lVdUZZYWZtU0ZPNmR1CnN4ZGhEZ3VUekR6bGZHME1LUXFuZjFCSTJiYVNqOWFURDVCandYV3RrcW1BcXhpNmluK29nVUlRdG5YUTRkUUYKV2piTjJ1ZDNPekRJZWpCN2hBMTBKQUhzTXVVTG9KcVF5ODFjdldnMVF1bG5JeFpyR0FLek9CcCswTmpqMnEraApJdjhybG5DakNJTHlLQjRSMEJCUkRZMGZ1cHF0cCtpbzR5Yno1QUJ0d2h1NXJYZFNtYlY1NlQ0cXVRSURBUUFCCm8yWXdaREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBakFkQmdOVkhRNEUKRmdRVStNV044L2hXUkZoRFRrRlhNbWJUZno5Z0JONHdId1lEVlIwakJCZ3dGb0FVK01XTjgvaFdSRmhEVGtGWApNbWJUZno5Z0JONHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSlMyUHFCdTcyUkNETmR2OU42alptMU1oRTBCClVjT09YQ05iSFZPR2puU1MrMFgwa2ppRG0xQWNhL0NmMXE4eWZmK0RpK0NKSlhXZ0g0RUpTbG5aTHRwZjkvWVIKc2dOUVRPK3VTSDRNaENyWEoxVEVVRHFadkhUTDhCNDBvd1hPZ0tNNGxOS2hIYS9VdEkwaGVaN2NJSktOaWY0Mwp5WVUxYjlxYlVLb3ljcm1zcUxzTXJPRjhKUE9rNDV4MWg3RWNZaWJkWGl1em03Z1VKVjdrVThpWFZKaXpjNjdMCkpJSVRMeGRrUmtpa01LUFp5WWVDVW8wZFcwZmdjRmdjL1FSY0MwcENxbEljUkY1RXFwdGhRNWpuQUZHSkNXdHAKcmZKSEdXNXNkMmZWenlnVlRwN21LcUdQdU1MeldHRENFRjNFZmxTSy94amJvdHVQSy93bFRMTEpCdFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQwRENDQXJpZ0F3SUJBZ0lVVVRsWEJWZStpK25abUZCV003WUhKL1lFaWtNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1lURUxNQWtHQTFVRUJoTUNRMDR4RVRBUEJnTlZCQWdUQ0VoaGJtZGFhRzkxTVFzd0NRWURWUVFIRXdKWQpVekVNTUFvR0ExVUVDaE1EYXpoek1ROHdEUVlEVlFRTEV3WlRlWE4wWlcweEV6QVJCZ05WQkFNVENtdDFZbVZ5CmJtVjBaWE13SUJjTk1qQXdOREV3TURneE9UQXdXaGdQTWpBM01EQXpNamt3T0RFNU1EQmFNR0F4Q3pBSkJnTlYKQkFZVEFrTk9NUkV3RHdZRFZRUUlFd2hJWVc1bldtaHZkVEVMTUFrR0ExVUVCeE1DV0ZNeEREQUtCZ05WQkFvVApBMnM0Y3pFUE1BMEdBMVVFQ3hNR1UzbHpkR1Z0TVJJd0VBWURWUVFERXdsMGFXeHNaWEl3TURFd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFESmlaelQ0cE9Xdnl0RUJIRWpWQWFldkxzRzJPbnoKMmZtQW1iMGUvallDRDV5azlXMnZmVC9OMG8rSGF3UllIQjdjUytISHBucGNGeHhZSlRHVzMrMHJoYkFrMGRMSgpSazhZMjg0Y1k5SWFuMS9XV3dnbmNqejR0RVV1bWMvbjFMNEVYVDdkaENIcGM2VlF0V2NNV00vTjVTVll1ZkdBClVSVTE0bzVUTWZuSng3TUdZL3BLUkdwbGk1ZE5iSWRGWHh5ZXM2Zllkdm9ZTW85K3lnVUJVUmthQmwxd1BBbGUKdjJZZVdjR2RnODNUQWNOb2tQMWZRZHo0MjlCTEZGcWRIZUxMVDl4V0pRN1BRbkV3YmFJWjNyMXVCL2xmR25PYwpncW9XR0g3bU91dWlabSttbzExL2lLeTJpTTErTXRUMnZFNjR4YlJLWEUvYTN0MzJhbGZPZjd0OUFnTUJBQUdqCmZ6QjlNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFkQmdOVkhRNEVGZ1FVQjdESS8wQkhpbDlaOVlpc0daNnJ5ZEZVYVRVdwpId1lEVlIwakJCZ3dGb0FVK01XTjgvaFdSRmhEVGtGWE1tYlRmejlnQk40d0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBR0NOWkFneEpUOStmbU9BbVFPWGdDdTlRWUlWN0VsSGpSMmtJS3d1Y3JEV1BKUGdVZlRjeFFvaEZIMEEKRTk3UGVGN0tJUWRjTitWMVlVWFh0eTVOVWs4cnVnNzRnNk1lNUxrOWJXNVhGbHlWbGhGRytwQWdiWWE1N2JGbwpjRjVhMDZVWElnZklHVHVQb0Q2RVR1dmQ2d0Z0eklwTzlORVhVWkZoOVdrUTZlUmlZZjJ3ekxncnc4V1hja0Q4ClI5OVJIditPdVdKYnJKVHVVU0FBK2h4NGZQRzZJMkJ1TUxid0FPblpVdFR4ZHVLUlFHMjB2K3B2dXlOR2g0dFEKQi9oVkczRXdqakJEYXNPWDB2dzg3a0wvK2cxckJqR2xPc2hueVhRdTFxYUttWURKK2paT0p6THc1aUhNYlFBdQpsYmtMNSs0RlpKZ0xLRG4vR2ZTMm10WWF3ODQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBeVltYzArS1RscjhyUkFSeEkxUUducnk3QnRqcDg5bjVnSm05SHY0MkFnK2NwUFZ0CnIzMC96ZEtQaDJzRVdCd2UzRXZoeDZaNlhCY2NXQ1V4bHQvdEs0V3dKTkhTeVVaUEdOdk9IR1BTR3A5ZjFsc0kKSjNJOCtMUkZMcG5QNTlTK0JGMCszWVFoNlhPbFVMVm5ERmpQemVVbFdMbnhnRkVWTmVLT1V6SDV5Y2V6Qm1QNgpTa1JxWll1WFRXeUhSVjhjbnJPbjJIYjZHREtQZnNvRkFWRVpHZ1pkY0R3SlhyOW1IbG5CbllQTjB3SERhSkQ5ClgwSGMrTnZRU3hSYW5SM2l5MC9jVmlVT3owSnhNRzJpR2Q2OWJnZjVYeHB6bklLcUZoaCs1anJyb21adnBxTmQKZjRpc3Rvak5makxVOXJ4T3VNVzBTbHhQMnQ3ZDltcFh6bis3ZlFJREFRQUJBb0lCQUNsT1F3NUtTZVdEbU9KLwo1cEJQRUd4SVVpeTlHSFlhSHNEMHdZWXdvL0VZTWdxOUlwWHRIYjZaZ1VGSDljUDVQM24zTTNjdjc3UWdLSGNJCmFIbDd1NmhINWlvbHR3WDVtd3lGUUdFaE5GYXdnM3Z6ZkdCWlVaWEhuTVpJVUF3NzFoWWU1bHVRVVVML3FNbzUKNDd6c0Z1c2tJOXRqZ05QRHlvMFl1Z0xqSTBidmdlck9rRGVpZFAyQ3ZkOVE5SUszd0xlR0thdXBYZWE4dmVYZgpWWW9nRmxIK0JzN04yU2JaZ1hLd3VKM3l5QzN2aUJReGlQdXJBa3JWQ3BrY0lZN3hHbDB5ZGs2L0QxbmNGMWgyClNLbEtUUXZob1hiMHFaUXF6RHdsU0QyTEF3SlBEelh0VjZmYlllWnJpVm5Ha0ZweG1vaHRSdXAyZk9HTWU0VUkKdHJRc0lpRUNnWUVBNXQ3bnRDQllXV2JyUVhjZkl0NmNiTkJKZlcvWFZxeUpBckQvSUp6OUpROUxvZVpaajZkNwpFN1hBbjlvVUJxMzZvZEt3L0Y3Uzk2QURYekhma0xkQjMxRU93bUtWS2Z6SkxXVVZhMGtUamFhS1E3WE4rbW9QCk4zOG5UUHY1WVBqdjJ2K2ZnVXF0SHI0a0JiU1phMS9zOEduZ3E5N202eVB3ancxb1daNnowYU1DZ1lFQTMzbGEKaFNzK1VCNVlkT2J4cndya0trRS9UR0FHL0FFdnlndzB5NExlRll2S1JQbmMxYmdoalh6VjU3SnlqdDV3WCtBWgpGUWRlN052NzNUeHpqbUFYVE5sTi9xTE5ZRTZGSW5mODNMYURHV2FMVklhU0pJODVDeFRhMmJ1SnBuWi9qQ3ZpCk5jTEFPb2l1UnJIM3dIcVF3cGlLeUR2djF6aGFkM0JTYlQ3V1VGOENnWUFsWWlxNnJCSWlSOXdJT2JXOCs3YncKbDdtT3FqR0FRMmZjRzdUMEh2ZU9ySzllZytJMHRMWGxOeVQ5dlY1SXhwc3k0Tjd2dnBzQ3BkSmw4N2x6d1hqVgpKRmJ6ZXVzVVpXNWQvMlE4ZnhTL2R4d2tZcWY3eUhpMlQ4eVpWcVBHNUFoU3VkbW1JZVZ1ZVBOMFNRNGVxT1hBCitDUDlNSmJMdElJYlo5eGh4cVR2YVFLQmdRRE5oeHliY1dRRDU0VFBMeitFRDI0ODlua3kwdlpaZXZYcXkwTWIKRUtjVUJkYm5qUzF2V2NOeUR5Zmp5aGpXRVBvbEUwTytOV00yVURQYUN5anovcWd2UTRRWjlyMFFIK2NPQm5DRwp4VXpaWlpnckN3RUpvcmVCMjVKVHdja2RVY3FJcml1RDZqTkZJa08yUFNOdzRNaVdVQmtEZ3l4WU1qbnhzMW43Cm8xa1QzUUtCZ0hkMlhQMUFobllKVHNBZndCb2NBa3lwV0lmTGUxUDRpWEdmcFNMWmtmWTl6Nml6Vy9uc2ROVFkKeFBsbXN0Mk9GWWMvOUluWi9zalRtTkJzR3ZTTjkzK2ovUHlBbHh5enZnckJvak81OGwzY2NMWWlJdm5qbFBGZAowdnpsbmNvMGFXU2VJUnFqQlNNMndVRWpqS3RDejNNQkNxaDlsci83ZVBmdzBVNGEySmg5Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-secret
  namespace: kube-system
type: Opaque

...
