{
 "title": "Cilium Metric",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(cilium_process_start_time_seconds,instance)"
   },
   {
    "name": "pod",
    "query": "label_values(cilium_process_start_time_seconds{kubernetes_namespace=\"kube-system\",instance=\"$server\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "packet_forward1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.1:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.11:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.12:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.13:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.14:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.21:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.22:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.23:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.3:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.4:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.5:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.8:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    }
   ]
  },
  {
   "title": "packet_forward2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.24:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.25:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.26:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.27:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.29:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.30:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.31:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.32:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.33:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.17:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.18:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    }
   ]
  },
  {
   "title": "packet_forward3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.34:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.35:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.36:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.37:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.39:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.40:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.41:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.43:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.45:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.19:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.20:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{instance=\"10.0.0.47:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cilium_process_resident_memory_bytes{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "process_resident_memory_bytes"
    },
    {
     "expr": "cilium_process_virtual_memory_bytes{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "process_virtual_memory_bytes"
    }
   ]
  },
  {
   "title": "Cilium Drop Count (EGRESS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_drop_count_total{direction=\"EGRESS\",kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "{{  reason }}"
    }
   ]
  },
  {
   "title": "Cilium Drop Count (INGRESS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_drop_count_total{direction=\"INGRESS\", kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Process FD Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_process_open_fds{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "process_open_fds"
    }
   ]
  },
  {
   "title": "L7 Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_l7_denied_total{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "L7_denied_total"
    },
    {
     "expr": "cilium_policy_l7_forwarded_total{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "L7_forwarded_total"
    }
   ]
  },
  {
   "title": "L7 Parse Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_l7_parse_errors_total{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "l7_parse_errors"
    }
   ]
  },
  {
   "title": "Policy Version History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_max_revision{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "policy revisions"
    }
   ]
  },
  {
   "title": "Cilium Policy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_count{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "policy_count"
    },
    {
     "expr": "cilium_policy_import_errors{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "policy_import_errors"
    }
   ]
  },
  {
   "title": "Total Endpoint Regenerations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_endpoint_regenerations{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "endpoint_regenerations"
    }
   ]
  },
  {
   "title": "Controllers Failing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_controllers_failing{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "controllers_failing"
    }
   ]
  },
  {
   "title": "Cilium Endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_endpoint_count{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "cilium_endpoint_count"
    }
   ]
  }
 ]
}