{
 "title": "Kubernetes Nodes (prometheus)",
 "description": "Kubernetes Nodes (prometheus)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=\"$server\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"$server\"} - node_memory_MemFree{instance=\"$server\"} - node_memory_Buffers{instance=\"$server\"} - node_memory_Cached{instance=\"$server\"}",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers{instance=\"$server\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached{instance=\"$server\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree{instance=\"$server\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((node_memory_MemTotal{instance=\"$server\"} - node_memory_MemFree{instance=\"$server\"}  - node_memory_Buffers{instance=\"$server\"} - node_memory_Cached{instance=\"$server\"}) / node_memory_MemTotal{instance=\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_read{instance=\"$server\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_bytes_written{instance=\"$server\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (rate(node_disk_io_time_ms{instance=\"$server\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\",instance=\"$server\"}) - sum(node_filesystem_free{device!=\"rootfs\",instance=\"$server\"})) / sum(node_filesystem_size{device!=\"rootfs\",instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes{instance=\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Apps",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(container_memory_usage_bytes, namespace)"
   },
   {
    "name": "app_name",
    "query": "label_values(container_memory_usage_bytes{namespace =~\"$namespace.*\"}, pod_name)"
   },
   {
    "name": "pod_name",
    "query": "label_values(container_memory_usage_bytes{pod_name =~\"$app_name.*\"}, pod_name)"
   },
   {
    "name": "container_name",
    "query": "label_values(container_memory_usage_bytes{pod_name =~\"$pod_name.*\",container_name!=\"POD\"}, container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate (container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",namespace=~'$namespace$',pod_name=~'$pod_name$',container_name=~'$container_name$'}[5m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{image!=\"\",container_name!=\"POD\",namespace=~'$namespace$',pod_name=~'$pod_name$',container_name=~'$container_name$'})",
     "legendFormat": "MEM Usage"
    }
   ]
  },
  {
   "title": "Network Input Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",namespace=~'$namespace$',pod_name=~'$pod_name$'}[5m]))",
     "legendFormat": "Network Input"
    }
   ]
  },
  {
   "title": "Network Output Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",namespace=~'$namespace$',pod_name=~'$pod_name$'}[5m]))",
     "legendFormat": "Network Output"
    }
   ]
  },
  {
   "title": "Network Input Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_packets_total{image!=\"\",namespace=~'$namespace$',pod_name=~'$pod_name$'}[5m]))",
     "legendFormat": "Input Packets"
    }
   ]
  },
  {
   "title": "Network Output Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_packets_total{image!=\"\",namespace=~'$namespace$',pod_name=~'$pod_name$'}[5m]))",
     "legendFormat": "Output Packets"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes Cluster Health (Prometheus)",
 "description": "Kubernetes Cluster Health (Prometheus)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Control Plane Components Down",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)"
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Crashlooping Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Node Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
    }
   ]
  },
  {
   "title": "Alerts Firing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  },
  {
   "title": "Alerts Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
    }
   ]
  }
 ]
}
{
 "title": "Cilium Metric",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(cilium_process_start_time_seconds,instance)"
   },
   {
    "name": "pod",
    "query": "label_values(cilium_process_start_time_seconds{kubernetes_namespace=\"kube-system\",instance=\"$server\"},kubernetes_pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "packet_forward1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.1:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.11:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.12:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.13:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.14:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.21:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.22:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.23:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.3:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.4:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.5:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.8:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{ direction }}"
    }
   ]
  },
  {
   "title": "packet_forward2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.24:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.25:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.26:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.27:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.29:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.30:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.31:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.32:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.33:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.17:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.18:9090\"}[4s])",
     "legendFormat": "{{ instance }}-{{direction}}"
    }
   ]
  },
  {
   "title": "packet_forward3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.34:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.35:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.36:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.37:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.39:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.40:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.41:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.43:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.45:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.19:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.20:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    },
    {
     "expr": "delta(cilium_forward_count_total{pod_template_generation=\"4\",instance=\"10.0.0.47:9090\"}[4s])",
     "legendFormat": "{{instance}}-{{direction}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cilium_process_resident_memory_bytes{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "process_resident_memory_bytes"
    },
    {
     "expr": "cilium_process_virtual_memory_bytes{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "process_virtual_memory_bytes"
    }
   ]
  },
  {
   "title": "Cilium Drop Count (EGRESS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_drop_count_total{direction=\"EGRESS\",kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "{{  reason }}"
    }
   ]
  },
  {
   "title": "Cilium Drop Count (INGRESS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_drop_count_total{direction=\"INGRESS\", kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Process FD Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_process_open_fds{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "process_open_fds"
    }
   ]
  },
  {
   "title": "L7 Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_l7_denied_total{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "L7_denied_total"
    },
    {
     "expr": "cilium_policy_l7_forwarded_total{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "L7_forwarded_total"
    }
   ]
  },
  {
   "title": "L7 Parse Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_l7_parse_errors_total{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "l7_parse_errors"
    }
   ]
  },
  {
   "title": "Policy Version History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_max_revision{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "policy revisions"
    }
   ]
  },
  {
   "title": "Cilium Policy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_policy_count{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "policy_count"
    },
    {
     "expr": "cilium_policy_import_errors{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "policy_import_errors"
    }
   ]
  },
  {
   "title": "Total Endpoint Regenerations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_endpoint_regenerations{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "endpoint_regenerations"
    }
   ]
  },
  {
   "title": "Controllers Failing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_controllers_failing{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "controllers_failing"
    }
   ]
  },
  {
   "title": "Cilium Endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_endpoint_count{kubernetes_pod_name=\"$pod\"}",
     "legendFormat": "cilium_endpoint_count"
    }
   ]
  }
 ]
}